#! /bin/sh

#       ██
#      ░██              ██████
#      ░██       ██████░██░░░██ ███     ██ ██████████  ██████  █████
#      ░██████  ██░░░░ ░██  ░██░░██  █ ░██░░██░░██░░██░░██░░█ ██░░░██
#      ░██░░░██░░█████ ░██████  ░██ ███░██ ░██ ░██ ░██ ░██ ░ ░██  ░░
#      ░██  ░██ ░░░░░██░██░░░   ░████░████ ░██ ░██ ░██ ░██   ░██   ██
#      ░██████  ██████ ░██      ███░ ░░░██ ███ ░██ ░██░███   ░░█████
#      ░░░░░   ░░░░░░  ░░      ░░░    ░░░ ░░░  ░░  ░░ ░░░     ░░░░░


sudo light -S 25 &
setxkbmap -option caps:swapescape &
# setxkbmap -option caps:ctrl_modifier &
c() { bspc config "$@" &  }
R() { bspc rule -a "$@" & }
s() { pkill -x "$1"; { sleep 0.1; "$@" & }; }

pgrep -x sxhkd > /dev/null || sxhkd &


# eww daemon &

# Set display from arandr saved script
# sh ~/.screenlayout/monitor.sh &

# Notifications
killall dunst
dunst --config $HOME/.config/dunst/dunstrc &

# Polkit
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# Wallpaper
# nitrogen --restore &
bash ~/.fehbg &

# Dex
dex -a -s /etc/xdg/autostart/:~/.config/autostart/  

# Picom
picom --experimental-backend --config $HOME/.config/picom/picom.conf &

# Network Applet
nm-applet --indicator &

# Clipboard manager
clipmenud &

# Cursor 
s xsetroot -cursor_name left_ptr 

# Bar
sh $HOME/.config/polybar/launch.sh & 
#                             GENERAL CONFIGURATION                           #

bspc monitor -d I II III IV V VI VII 

c border_width	3
c window_gap		1
c left_padding		0
c right_padding		0
c top_padding		4
c bottom_padding	4


#unixporn mode
# c bottom_padding	10
# c left_padding	60
# c right_padding	60
# c top_padding		80

# Border
c focused_border_color  "#163841"
c normal_border_color   "#111111"
c active_border_color   "#230B52"
c presel_feedback_color "#4c566a"

# c ignore_ewmh_fullscreen all
c split_ratio          	0.50
c borderless_monocle   	true
c gapless_monocle      	true
# c pointer_follows_focus true
c focus_follows_pointer true
c single_monocle        false
c initial_polarity first_child
c pointer_action2 resize_corner

#                                  WINDOW RULES                               #


R SimpleScreenRecorder 	desktop='^6'  state='floating' 
R Vscodium 		desktop='^1'
R Spotify 		desktop='^1'
R Gimp 			desktop='^7' state='floating' follow=on
R Google-chrome 	desktop='^3'
R "Vivaldi-stable" 		desktop='^1' 
R firefox 		desktop='^2' 
R discord 		desktop='^7'
R Ferdi 		desktop='^6' state='tiled'
R Emacs 		desktop='^1' state='tiled'
R mplayer2 		state='floating'
R Galculator 		state='floating'
R Alacritty 		state='floating'
R Pavucontrol		sticky=on
R mpv state='floating'  rectangle=640x360+100+100
R "YouTube Music" 		state='floating'  rectangle=950x900+20+120 sticky=on
R Yad 			state='floating'
R Kupfer.py	 	focus=on
# R Polybar 		manage=on

s touchegg
s unclutter --start-hidden -idle 5
# s borders &

