#! /bin/sh

#       ██
#      ░██              ██████
#      ░██       ██████░██░░░██ ███     ██ ██████████  ██████  █████
#      ░██████  ██░░░░ ░██  ░██░░██  █ ░██░░██░░██░░██░░██░░█ ██░░░██
#      ░██░░░██░░█████ ░██████  ░██ ███░██ ░██ ░██ ░██ ░██ ░ ░██  ░░
#      ░██  ░██ ░░░░░██░██░░░   ░████░████ ░██ ░██ ░██ ░██   ░██   ██
#      ░██████  ██████ ░██      ███░ ░░░██ ███ ░██ ░██░███   ░░█████
#      ░░░░░   ░░░░░░  ░░      ░░░    ░░░ ░░░  ░░  ░░ ░░░     ░░░░░


c() { bspc config "$@" &  }
R() { bspc rule -a "$@" & }
s() { pkill -x "$1"; { sleep 0.1; "$@" & }; }

pgrep -x sxhkd > /dev/null || sxhkd &


# eww daemon &
# Set display from arandr saved script
# sh ~/.screenlayout/monitor.sh &
# Bar
sh $HOME/.config/polybar/launch.sh
# Notifications
killall dunst
dunst --config $HOME/.config/dunst/dunstrc &
# Polkit
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
# Wallpaper
# nitrogen --restore &
bash ~/.fehbg &
# Dex
dex -a -s /etc/xdg/autostart/:~/.config/autostart/  
# Picom
picom --experimental-backend --config $HOME/.config/picom/picom.conf &
# Network Applet
nm-applet --indicator &
# Clipboard manager
clipmenud &

# Cursor and keyb
setxkbmap -option caps:swapescape &
xsetroot -cursor_name left_ptr &
xset r rate 230 30
sudo light -S 25 &

#                             GENERAL CONFIGURATION                           #


bspc monitor -d I II III IV V VI VII 

bspc config border_width         0
bspc config window_gap           0
# bspc config top_padding          36

# Border
bspc config focused_border_color        "#7373ff" 
# bspc config focused_border_color        "#7973b0"
# bspc config focused_border_color        "#ff3465" 
# bspc config focused_border_color        "#ffffff" 
# bspc config focused_border_color        "#504945"
bspc config normal_border_color         "#1e0f2c"
bspc config active_border_color         "#fb4934"
# bspc config active_border_color         "#230B52"
bspc config presel_feedback_color		"#4c566a"

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_follows_focus true
bspc config focus_follows_pointer true
bspc config single_monocle        false
bspc config initial_polarity first_child
bspc config pointer_action2 resize_corner

#                                  WINDOW RULES                               #



bspc rule -a Code desktop='^1'
bspc rule -a Spotify desktop='^7'
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Google-chrome desktop='^2'
bspc rule -a firefox desktop='^2' 
bspc rule -a Ferdi desktop='^6'
bspc rule -a mplayer2 state=floating
bspc rule -a galculator state=floating
# bspc rule -a kitty state=floating
bspc rule -a Pavucontrol state=floating
bspc rule -a Yad state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

s borders &
