#! /bin/sh
# vim:fileencoding=utf-8:ft=sh:foldmethod=marker

#       ██
#      ░██              ██████
#      ░██       ██████░██░░░██ ███     ██ ██████████  ██████  █████
#      ░██████  ██░░░░ ░██  ░██░░██  █ ░██░░██░░██░░██░░██░░█ ██░░░██
#      ░██░░░██░░█████ ░██████  ░██ ███░██ ░██ ░██ ░██ ░██ ░ ░██  ░░
#      ░██  ░██ ░░░░░██░██░░░   ░████░████ ░██ ░██ ░██ ░██   ░██   ██
#      ░██████  ██████ ░██      ███░ ░░░██ ███ ░██ ░██░███   ░░█████
#      ░░░░░   ░░░░░░  ░░      ░░░    ░░░ ░░░  ░░  ░░ ░░░     ░░░░░

# {{{ setup
# Bar
sudo light -S 25 &
xset r rate 230 30
setxkbmap -option caps:swapescape &
# setxkbmap -option caps:ctrl_modifier &
bspc monitor -d 1 2 3 4 5 6 7 8 9 10

c() { bspc config "$@" &  }
R() { bspc rule -a "$@" & }
s() { pkill -x "$1"; { sleep 0.1; "$@" & }; }
# }}}

# {{{ Autostart
pgrep -x sxhkd > /dev/null || sxhkd &
# eww daemon &
# Set display from arandr saved script
# sh ~/.screenlayout/monitor.sh &
# Notifications
killall dunst
dunst --config $HOME/.config/dunst/dunstrc &
# Polkit
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
# Wallpaper
# nitrogen --restore &
bash ~/.fehbg &
# Dex
dex -a -s /etc/xdg/autostart/:~/.config/autostart/  
# Picom
picom --experimental-backend --config $HOME/.config/picom/picom.conf &
# Network Applet
nm-applet --indicator &
# Clipboard manager
clipmenud &
# Cursor 
s xsetroot -cursor_name left_ptr 
# misc apps
s touchegg
s unclutter --start-hidden -idle 5
# s borders &
s playerctld daemon

notify-send "bg apps launched"
# }}}

# {{{ Bspc Configs
c border_width 0
c window_gap 0
c left_padding 0
c right_padding 0
c top_padding 0
c bottom_padding 0
#unixporn mode
# c bottom_padding	10
# c left_padding	60
# c right_padding	60
# c top_padding		80
# Border
# c focused_border_color  "#BBA6E6"
c focused_border_color  "#8EAFD1"
c normal_border_color   "#1A1B2A"
c active_border_color   "#8EAFD1"
c presel_feedback_color "#4c566a"
# c ignore_ewmh_fullscreen all
c split_ratio          0.50
c borderless_monocle   true
c gapless_monocle      true
c pointer_follows_focus false
c focus_follows_pointer true
c single_monocle        false
c initial_polarity first_child
c pointer_action2 resize_corner
notify-send "bspc configs set"
# }}}

# {{{ Bspc Rules
R SimpleScreenRecorder 	desktop='^5'  state='floating'
R Vscodium 		desktop='^1'
R Spotify 		desktop='^1'
R Gimp 			desktop='^7' state='floating' follow=on
# R Google-chrome 	desktop='^3'
R Slack 	desktop='^9'
R "Vivaldi-stable"  desktop='^1'		
R notion-app 		desktop='^4' 
R "discord" 		desktop='^10' 
R "obsidian" 		desktop='^3' 
R "Code" 		desktop='^5'  
R firefox 		desktop='^2' 
R Emacs 		desktop='^1' state='tiled'
R "Thunar" 		state='floating'
R "Pcmanfm" 		state='floating'
R mplayer2 		state='floating'
R Galculator 		state='floating'
# R Alacritty 		state='floating'
R Pavucontrol		sticky=on
R "motion_recorder" state='floating'  sticky=on rectangle=640x360+100+100
R mpv state='floating'  sticky=on rectangle=640x360+100+100
R scrcpy state='tiled'  sticky=on rectangle=469x1010
R "YouTube Music" 		state='floating'  rectangle=950x900+20+120 sticky=on
R "Dragon-drop" 		state='floating'  sticky=on
R Yad 			state='floating'
R Kupfer.py	 	focus=on
# R Polybar 		manage=on
# }}}

notify-send "bspc rules set"
bash $HOME/.config/polybar/launch.sh & 
notify-send "Launching Poly bar"
s xgamma -gamma 0.90   
