#!/usr/bin/env bash
set -u
set -s
# Source: https://stefanscherer.github.io/how-to-take-screenshots-with-drop-shadow/

convert "$1" \( +clone -background black15 -shadow 80x40+5+30 \) +swap -background transparent -layers merge +repage "$1-shadow.png"
