#!/usr/bin/env bash
selected=`cat ~/.cht-languages ~/.cht-command | fzf -i --height 10%`
if [[ -z $selected ]]; then
  exit 0
fi

read -p "Enter Query: " query

if grep -qs "$selected" ~/.cht-languages; then
  query=`echo $query | tr ' ' '+'`
  bash -c "echo \"curl cht.sh/$selected/$query/\" & curl cht.sh/$selected/$query "
else
  bash -c "curl -s cht.sh/$selected~$query "
fi

