#!/bin/sh
# folder=$(echo -en "configs\nscripts" | rofi -dmenu -p "chose folder")
# p="~/dotstow/bin/.local/bin"
# case $folder in
# 	"configs")
# find ~/dotstow/moun-tain -type f |grep -v .git | rofi -dmenu -auto-select -i -p "file" -lines 14 | xargs -r alacritty -e nvim
# ;;
# "scripts")
	# 	find ~/dotstow/gruv-dark/bin/.local/bin -type f |grep -v .git | rofi -dmenu -i -p "file" -lines 14 | xargs -r alacritty -e nvim

# esac


# find ~ -type f |grep -v .git | rofi -dmenu -i -p "file" -lines 14 | xargs -r alacritty -e nvim


FILES=$(find ~/dotstow/themes/cr0nus/ -type f |grep -v .git | fzf -m --no-sort --delimiter / --with-nth -2,-1)

if [ -n "$FILES" ]; then
kitty --detach nvim $FILES 
fi
