#!/bin/bash


if [ ! -f "$HOME/cookies.txt" ] ; then
  echo "~/cookies.txt not found"
  exit
fi

online="online"
offline="offline"
select="select"
shuffle="shuffle"
straight="straight"


  mode=$(echo -en "$select\n$shuffle\n$straight" | fzf -i +m --height 10% --reverse )


  case $mode in
    "shuffle") 
      c=$(echo -en "$online\n$offline" | fzf -i -x --height 10% --reverse )
      case $c in
        "online" ) echo -en "$online mode\n" ; mpv --shuffle --no-video --ytdl-raw-options="cookies=~/cookies.txt" https://music.youtube.com/playlist\?list\=LM 
          ;;
        "offline" ) echo -en "$offline mode\n" ; mpv --no-video --no-audio-display --shuffle ~/music/
          ;;
        *) echo "error in shuffle mode"
          ;;
      esac
      ;;
    "straight") mpv  --no-video --no-video --ytdl-raw-options="cookies=~/cookies.txt" https://music.youtube.com/playlist\?list\=LM 
      ;;
    "select") find ~/music/ -type f | fzf -i  --height 80% -m --reverse | xargs -r mpv  --no-video --no-audio-display  
              mpv  --no-video --no-audio-display --shuffle ~/music/
      ;;
    *) echo "error in mode"
      ;;
  esac





# mpv --shuffle --no-video --ytdl-raw-options="cookies=~/cookies.txt" https://music.youtube.com/playlist\?list\=LM 
# mpv --no-video --ytdl-raw-options="cookies=~/cookies.txt" https://music.youtube.com/playlist\?list\=LM 
