#!/bin/bash

# Input validation
if [ ! -d "$HOME/music" ]; then
  echo "Music directory not found"
  exit
fi

if [ ! -f "$HOME/cookies.txt" ]; then
  echo "~/cookies.txt not found"
  exit
fi

export FZF_DEFAULT_OPTS=" -1 -i 
--prompt 'yt-music launcher ⯈ ' 
--marker=+ 
--cycle
--keep-right  
--color=gutter:-1,pointer:#ff3c3c,info:#0dbc79,hl:#0dbc79,hl+:#23d18b 
--reverse 
--height 100%
--color=fg:250,fg+:15,hl:203,hl+:203  
--color=bg:#0c1014,gutter:-1,pointer:#ff3c3c,info:#0dbc79
--bind 'btab:toggle-up,tab:toggle-down'
--bind='?:toggle-preview'
--bind='ctrl-u:preview-page-up'
--bind='ctrl-d:preview-page-down'
--preview-window 'right:60%:wrap'
"
# Variables
online="online"
offline="offline"
select="select"
shuffle="shuffle"
straight="straight"

  mode=$(echo -en "$select\n$shuffle\n$straight" | fzf -i +m --height 10% --reverse )


  case $mode in
    "shuffle") 
      c=$(echo -en "$offline\n$online" | fzf -i -x --height 10% --reverse )
      case $c in
        "online" ) echo -en "$online mode\n" ;  mpv --input-ipc-server=/tmp/mpvsocket --shuffle --no-video --ytdl-raw-options="cookies=~/cookies.txt" https://music.youtube.com/playlist\?list\=LM 
          ;;
        "offline" ) echo -en "$offline mode\n" ;  mpv --input-ipc-server=/tmp/mpvsocket --no-video --no-audio-display --shuffle ~/music/
          ;;
        *) echo "error in shuffle mode"
          ;;
      esac
      ;;
    "straight")  mpv --input-ipc-server=/tmp/mpvsocket  --no-video --no-video --ytdl-raw-options="cookies=~/cookies.txt" https://music.youtube.com/playlist\?list\=LM 
      ;;
    "select") find ~/music/ -type f | fzf -i  --height 80% -m --reverse | xargs -r  mpv --input-ipc-server=/tmp/mpvsocket  --no-video --no-audio-display  
               mpv --input-ipc-server=/tmp/mpvsocket  --no-video --no-audio-display --shuffle ~/music/
      ;;
    *) echo "error in mode"
      ;;
  esac





#  mpv --input-ipc-server=/tmp/mpvsocket --shuffle --no-video --ytdl-raw-options="cookies=~/cookies.txt" https://music.youtube.com/playlist\?list\=LM 
#  mpv --input-ipc-server=/tmp/mpvsocket --no-video --ytdl-raw-options="cookies=~/cookies.txt" https://music.youtube.com/playlist\?list\=LM 
