#!/bin/sh
#shorten url not so quick though
if [ -f "$1" ] ; then
	temp="file=@"
else
	temp="shorten="
fi

link=$(curl -F"$temp$1" https://0x0.st 2> /dev/null)
if [ ! -z "$link" ] ; then
	echo "$link"
	echo "$link" | xclip -selection clipboard
fi
