#!/usr/bin/env bash

p="/tmp/$(date +"%d-%m-%y-%M").png"

# maim -u -o -s $p && add-shadow $p
maim -u -o -s $p
# 0x $p


xclip -selection clipboard -target image/png -i $p
dragon-drop -x $p &


# notify-send "Screenshot launched!"
notify-send -i $p "screen_copy" "Screenshot copied to clipboard!"

