#!/usr/bin/env bash

p="/tmp/$(date +"%d-%m-%y-%M").png"

# maim -u -o -s $p && add-shadow $p
maim -u -o -s $p
# 0x $p


xclip -selection clipboard -target image/png -i $p
# dragon-drag-and-drop -x $p-shadow.png &


# notify-send "Screenshot launched!"
notify-send "Screenshot copied to clipboard!"

