#!/bin/bash

# ss: minimal screenshot script for sharex hosts
# check ssf for more details
# https://github.com/TorchedSammy/dotfiles

# maim -u -o -s /tmp/screenshot.png
# if [[ $? == 1 ]]; then exit 1; fi
# notify-send -t 2000 "Screenshot taken, uploading..."
# ssf /tmp/screenshot.png


p="/tmp/$(date +"%d-%m-%y-%M").png"

maim -u -o -s $p


# 0x $p

xclip -selection clipboard -target image/png -i $p

notify-send "Screenshot copied to clipboard!"
