#!/bin/sh


echo $(find ~/dotstow/ -type d | grep -v .git | rofi -dmenu -auto-select -i -p "theme" -lines 14 )

# for i in "$@";do

# mkdir -p $i/.config/
# cp -r ~/.config/$i $i/.config/
# echo $i

# done
