#!/bin/bash
word=` rofi -dmenu -i -p "search" -lines 0`
if [ -z "$word" ];
then (echo "Forgot URL?"; exit 1);
else 
  URL=$(gh issue create --repo umgbhalla/db --label "cli" --title "$word" --body "" | sed -e 's/github.com\/umgbhalla\/db\/issues/hi.umgbhalla.xyz\/i/g' | tr -d '\n' )
  notify-send "shortened to $URL"
  echo $URL | tr -d '\n' | copy
fi


