#!/bin/bash
# You can call this script like this:
# $./volume up
# $./volume down
# $./volume mute

function get_volume {
  pamixer --get-volume
}

function is_mute {
  pamixer --get-mute > /dev/null
}

function send_notification {
  volume=`get_volume`
  bar=$(seq -s "─" 0 $(($volume / 5)) | sed 's/[0-9]//g')
  if [ "$volume" = "0" ]; then
    icon_name="/usr/share/icons/Faba/48x48/notifications/notification-audio-volume-muted.svg"
    bar=""
  else
    if [  "$volume" -lt "10" ]; then
      icon_name="/usr/share/icons/Faba/48x48/notifications/notification-audio-volume-low.svg"
    else
      if [ "$volume" -lt "30" ]; then
        icon_name="/usr/share/icons/Faba/48x48/notifications/notification-audio-volume-low.svg"
      else
        if [ "$volume" -lt "70" ]; then
          icon_name="/usr/share/icons/Faba/48x48/notifications/notification-audio-volume-medium.svg"
        else
          icon_name="/usr/share/icons/Faba/48x48/notifications/notification-audio-volume-high.svg"
        fi
      fi
    fi
  fi
  # Send the notification
  # dunstify " Volume " "$bar" -i $icon_name -r 5555 -u normal

  dunstify " Volume : $volume% " -u NORMAL -h int:value:$(($volume)) -h string:x-canonical-private-synchronous:volume
  # dunstify " Volume : $volume% " -i $icon_name -r 5555 -u normal -h int:value:$(($volume)) 
  
  # notify-send.sh "Volume : $volume" -i "$icon_name" -t 2000 --replace=555
}

case $1 in
  up)
    pactl set-sink-volume @DEFAULT_SINK@ +1% > /dev/null
    send_notification
    ;;
  down)
    pactl set-sink-volume @DEFAULT_SINK@ -1% > /dev/null
    send_notification
    ;;
  mute)
    # Toggle mute
    pactl set-sink-mute @DEFAULT_SINK@  toggle > /dev/null
    if is_mute ; then
      icon_name="/usr/share/icons/Faba/48x48/notifications/notification-audio-volume-muted.svg"
      # dunstify "Mute" -i $icon_name -r 5555 -u normal -h int:value:0
      dunstify "Mute" -u NORMAL -h int:value:0 -h string:x-canonical-private-synchronous:volume
    else
      send_notification
    fi
    ;;
esac
